server:
  port: 8080

const:
  solt: default

spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/java?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 111


mybatis-plus:
  mapper-location:- classpath: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: assign_id
      table-underline: true
    banner: false